name: admin_repository
description: "A repository to manage admin-specific data operations."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  equatable: ^2.0.7
  logistcs:  # Dependency on the main app to access ApiClient
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true