name: auth_repository
description: "A dart file to manage users authentication."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  http: ^1.2.2
  shared_preferences: ^2.2.0
  logistcs: # Add the main app as a dependency
    path: ../.. # Path to the root of the main app (adjust if the structure differs)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true